[versions]
agp = "8.7.3"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
appcompat = "1.7.0"
material = "1.12.0"
lifecycle = "2.8.4"
material3 = "1.3.1"
flowlayout = "1.4.3"
activity-ktx = "1.8.0"

# plugins
kotlinPlugin = "1.9.22"
kspPlugin = "1.9.22-1.0.16"
ktlintPlugin = "11.4.2"
detektPlugin = "1.23.0"
googleServicePlugin = "4.3.15"
hiltPlugin = "2.48"

# auth
kakao-user = "2.14.0"
naver-login = "5.8.0"
google-services = "4.3.10"
firebase-auth = "21.0.1"
firebase-bom = "29.0.0"
play-services-auth = "19.2.0"

## hilt
hilt = "2.48"
hilt-navigation-compose = "1.2.0"

## coroutine
corotine-core = "1.7.3"

## network
retrofit = "2.9.0"
logging-interceptor = "4.11.0"

# logging
timber = "5.0.1"

# preference
datastore = "1.1.1"

# webview
androidx-webkit = "1.5.0"

# glide
glide = "4.12.0"

# lottie
lottie = "6.1.0"

# compose
androidx-compose-bom = "2024.11.00"
androidx-navigation-compose = "2.8.4"
androidx-splashscreen = "1.0.1"
androidx-lifecycle-compose = "2.8.7"
composeCompiler = "1.4.8"

# related compose UI
accompanist-compose = "0.28.0"
coil-compose = "2.4.0"


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinPlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektPlugin" }
google-service = { id = "com.google.gms.google-services", version.ref = "googleServicePlugin"}
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltPlugin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinPlugin" }
kotlinKsp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
flowlayout = { group = "androidx.compose.foundation", name = "foundation", version.ref = "flowlayout" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }

# hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

# auth
kakao-user = { group = "com.kakao.sdk", name = "v2-user", version.ref = "kakao-user" }
naver-login = { group = "com.navercorp.nid", name = "oauth", version.ref = "naver-login" }
#noinspection SimilarGradleDependency
google-services = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "google-services" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebase-auth" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-services-auth" }

# coroutine
coroutine-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "corotine-core" }

# network
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }

# logging
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "androidx-webkit" }

# glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

# lottie
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

# compose
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle-compose" }
compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "composeCompiler" }

# related compose UI
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist-compose" }
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist-compose" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist-compose" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }

[bundles]
retrofit = ["retrofit", "converter-gson", "logging-interceptor"]
